### ISSUE TITLE
Juandi - Selección programa para SouceMeter: phpMyAdmin, versiones: 5.2.0-rc1 / 5.1.3 / 4.9.10

### ISSUE THREAD

**Issue by joa102** [PRIS2/SourceMeterJoa102#1]
Selección programa **phpMyAdmin** para las versiones:
**5.2.0-rc1** -> https://github.com/phpmyadmin/phpmyadmin/releases/tag/RELEASE_5_2_0RC1
**5.1.3** -> https://github.com/phpmyadmin/phpmyadmin/releases/tag/RELEASE_5_1_3
**4.9.10** -> https://github.com/phpmyadmin/phpmyadmin/releases/tag/RELEASE_4_9_10

**Comment by imaguila** [comment]
Ok

**Comment by joa102** [comment]
Finish
